site_name: Code-to-Docs Agent Demo
site_description: A demonstration of automatic documentation generation from code
site_author: Code-to-Docs Agent

nav:
  - Home: index.md
  - API Reference: api/index.md

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences